### ISSUE TITLE
library(hrbrmisc): What is it?

### ISSUE THREAD

**Issue by vitallish** [52vis/2016-13#2]
Hello,

I'm having trouble installing/finding any information on `hrbrmisc` library which is causing the line:
`gg <- gg + theme_hrbrmstr(grid="Y", axis="X")` to fail. 

Where can I find this library?

**Comment by vitallish** [comment]
sorry found it here: https://github.com/hrbrmstr/hrbrmisc

**Comment by hrbrmstr** [comment]
k. my theme wasn't really a show-stopper (cld use any or none)
